### ISSUE TITLE
Accelerometer Multithreading

### ISSUE THREAD

**Issue by michaelb18** [VTBajaTesting/testing-suite#22]
Make the Accelerometer class have a target function to start a thread. We will need to do some linkage sorcery, but it is possible to have a member of the Accelerometer(and other Sensor Classes) be the target function for our threads. The member function *should* (famous last words) have access to all of Accelerometer's members.

**Comment by michaelb18** [comment]
@keithmyburgh - One more requirement for the Accelerometer class: the thread should end after 60 seconds or when the switch is flipped, whichever comes first.

**Comment by keithmyburgh** [comment]
I thought all of the multithreading was being done in the main file. I
haven’t touched that yet, just got my code running error free while
reporting my readings in the new format

**Comment by michaelb18** [comment]
closing because multithreading breaks beaglebones
